apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: p9bbnvl2i-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p9bbnvl2i-python 
  name: p9bbnvl2i-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: p9bbnvl2i-python
    weight: 100 
